### ISSUE TITLE
Environment variable substitution in project.json

### ISSUE THREAD

**Issue by oserban** [ove/ove-asset-manager#111]
Project.json files should allow several environment variables to be substituted:
- AM_SERVER
- AM_PROXY_SERVER
- OVE_HOST
- PROJECT/asset/LATEST <- with the asset's latest version

**Comment by jamesscottbrown** [comment]
I thought that at the end of our discussion yesterday you decided that you wanted this substitution to be done by the Read Proxy, rather than the AM?

**Comment by oserban** [comment]
AM Read proxy is part of the same AM ecosystem
