### ISSUE TITLE
Ugly URLs for files expanded from zip files

### ISSUE THREAD

**Issue by jamesscottbrown** [ove/ove-asset-manager#115]
Supposes I upload a file `amr.zip` to a project called `amr`.

This file will be stored at `AM_HOST/dev-store/amr/amr_zip/1/amr.zip`

After expanding with the zip worker, a file that was inside will be available at a URL like: `AM_HOST/dev-store/amr/amr_zip/1/BsHcNJwql7HGsNom2C36M/amr/amr/README.md` 

**AM_HOST/dev-store/amr/amr_zip/1/** amr.zip
**AM_HOST/dev-store/amr/amr_zip/1/** *BsHcNJwql7HGsNom2C36M/amr/amr* /README.md

The middle part (`BsHcNJwql7HGsNom2C36M/amr/amr`) seems unnecessarily long.

**Comment by oserban** [comment]
Just be careful that by simplifying the URL, you may make the resource non unique or introduce extra complexity in the read proxy.

**Comment by oserban** [comment]
I think this is dangerous to implement as it introduces other performance issues
