### ISSUE TITLE
Show creation date in project table

### ISSUE THREAD

**Issue by jamesscottbrown** [ove/ove-asset-manager#14]
The projects in the project list can currently only be sorted by Project Name, and whether or not they contain a project.json file.

It would be very useful to also have a column listing the project creation date.

**Comment by senakafdo** [comment]
While this is useful, I think it would be more useful to display the last updated time (suitably formated of course) of an asset, compared to the project creation date. The need for this is mostly short term, in the long term project creation would not be much of a useful thing to know compared to when was something in it was last updated, which then would lead to the question of which of the assets within the project were last updated; and hence this request.

**Comment by oserban** [comment]
The creation date of a s3 bucket is part of the protocol  so it can be displayed easily. The update date is harder because this is not part of the s3 bucket standard. I will have to scan recursively all the assets in the project and this is a really expensive operation.
