### ISSUE TITLE
Creating new projects fails

### ISSUE THREAD

**Issue by jamesscottbrown** [ove/ove-asset-manager#167]
After entering the name of a project, the user is shown an error complaining that the `project_id` is missing, despite this field having been automatically populated based on the name.

![bug-creating-projects](https://user-images.githubusercontent.com/338833/63863643-78cd8600-c9a6-11e9-803b-db56c48ebd48.png)

**Comment by jamesscottbrown** [comment]
This is because the value of a `readOnly` element is not included when the form is submitted. However, as the project_id is programamtically generated from the project name, the same transformation can be done on the server.

**Comment by oserban** [comment]
That's a hack because we can't guarantee consistency if we regenerate the id on the server side. We can include the id manually before submitting the form.

**Comment by oserban** [comment]
Closed by #169
