### ISSUE TITLE
OOM exception when uploading large files

### ISSUE THREAD

**Issue by oserban** [ove/ove-asset-manager#227]
[2019-11-07 13:22:07,406] [DEBUG] Handling api exception: MemoryError()

For a 1.5GB tiff image

**Comment by jamesscottbrown** [comment]
I don't think this is super suprising: it looks like the new AM VM only has 4 GB of RAM, and is currently using 75% of that just sitting idle. 

If we increase to 8 GB of RAM we should have enough headroom to handle most uses.

**Comment by oserban** [comment]
Increasing the memory on the machine fixed the problem
