### ISSUE TITLE
Link to latest version of asset

### ISSUE THREAD

**Issue by jamesscottbrown** [ove/ove-asset-manager#54]
Assets are version controlled, with a separate URL for each version of a file (`http://asset-store-host/<store_name>/<project_name>/<asset_name>/1/<asset_name>.<extension>`).

This means that updating an asset also requires updating the `project.json` file.

It would be convenient if the read proxy exposed a link that returned whatever is the latest version of a file, rather than an specific version number (e.g. `http://asset-store-host/<store_name>/<project_name>/<asset_name>/latest/<asset_name>.<extension>`)

**Comment by oserban** [comment]
With the current design, this could be potentially dangerous:

- When you update an asset, it may not have the same structure as the previous version
- If you are getting the index file only for the current version, this changes when a worker processes the asset which may make it invalid for the current user

I think there are more dangerous scenarios than advantages for this feature so unless we come up with a better solution I am closing this for now.
