### ISSUE TITLE
Optimize the dzi worker build

### ISSUE THREAD

**Issue by oserban** [ove/ove-asset-manager#86]
Currently the libvips library is rebuilt at every release. We should split this into to docker images and release them separately.

**Comment by senakafdo** [comment]
Was amazed to see this issue and then came across https://hub.docker.com/search?q=libvips&type=image&sort=updated_at&order=desc. +1 for releasing a libvips base image, and potentially keeping it in sync with the vips releases in generally. That would be a huge plus not just for OVE/AM but for anyone who is interested in using libvips.
