### ISSUE TITLE
Add Worker Documentation on Read the Docs

### ISSUE THREAD

**Issue by senakafdo** [ove/ove-asset-manager#88]
The linking is straightforward and needs to be done in ove-docs.

But, in addition to the linking, we also need to explain what the worker does, what file types it can work with and what technology it is based on. If there are parameters that can be passed through a user interface, then we need to include a screenshot of the UI explaining how to provide these parameters.

**Comment by oserban** [comment]
I agree with you that we need to expand the worker documentation. It will
be linked automatically to the readthedocs documentation anyway 😉

**Comment by oserban** [comment]
Done. See https://github.com/ove/ove-docs/pull/34
